Algoritmo "Exercicio_4"

// Disciplina   : Algoritmo
// Professor   : Leandro Gonzalez
// Descrição   : Imprime apenas os números pares de 1 até 100
// Autor(a)    : Leandro Lima
// Data atual  : 22/04/2025

Var

   i, n_pares : inteiro

Inicio

   para i de 1 ate 100 faca
      se i mod 2 = 0 entao
         n_pares <- i
         escreval("Números Pares: ", n_pares)
      fimse
   fimpara


Fimalgoritmo