Algoritmo "Exercicio_2"
// Disciplina   : Algoritmo
// Professor   : Leandro Gonzalez
// Descrição   : Imprime o quadrado de cada número
// Autor(a)    : Leandro Lima
// Data atual  : 22/04/2025

Var
   numero, i, quadrado : inteiro

Inicio

   para i de 1 ate 100 faca
      escreva("Digite o", i,"º número: ")
      leia (numero)
      quadrado <- numero * numero
      escreval("O quadrado de", numero," é:", quadrado)
   fimpara

Fimalgoritmo